// Generates supabase/seed.sql from seed/catalog.ts. Run: npm run db:seed-sql
import { writeFileSync } from "node:fs";
import { seedCategories, seedProducts } from "../seed/catalog.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]`;

const lines: string[] = [
  "-- GENERATED by `npm run db:seed-sql` from seed/catalog.ts. Do not edit by hand.",
  "-- Re-running is safe: rows are matched on slug.",
  "",
];

for (const c of seedCategories) {
  lines.push(
    `insert into public.categories (slug, name, tagline, image_url, sort_order) values (${q(c.slug)}, ${q(c.name)}, ${q(c.tagline)}, ${q(c.imageUrl)}, ${c.sortOrder}) on conflict (slug) do nothing;`,
  );
}
lines.push("");
for (const p of seedProducts) {
  lines.push(
    `insert into public.products (slug, name, description, price_cents, category_id, image_url, sizes, stock, featured) select ${q(p.slug)}, ${q(p.name)}, ${q(p.description)}, ${p.priceCents}, c.id, ${q(p.imageUrl)}, ${arr(p.sizes)}, ${p.stock}, ${p.featured} from public.categories c where c.slug = ${q(p.categorySlug)} on conflict (slug) do nothing;`,
  );
}

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${seedCategories.length} categories, ${seedProducts.length} products)`);
