// Generates supabase/seed.sql and frontend/lib/features/catalog/data/seed_catalog.dart
// from seed/catalog.ts. Run: node scripts/generate-seed.ts
import { writeFileSync } from "node:fs";
import { seedCategories, seedProducts, seedReviews } from "../seed/catalog.ts";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]`;

const sql: string[] = [
  "-- GENERATED by `node scripts/generate-seed.ts` from seed/catalog.ts. Do not edit by hand.",
  "-- Re-running is safe: rows are matched on slug.",
  "",
];
for (const c of seedCategories) {
  sql.push(`insert into public.categories (slug, name, tagline, image_url, sort_order) values (${q(c.slug)}, ${q(c.name)}, ${q(c.tagline)}, ${q(c.imageUrl)}, ${c.sortOrder}) on conflict (slug) do nothing;`);
}
sql.push("");
for (const p of seedProducts) {
  sql.push(`insert into public.products (slug, name, description, price_cents, category_id, image_url, sizes, stock, featured, colors, images) select ${q(p.slug)}, ${q(p.name)}, ${q(p.description)}, ${p.priceCents}, c.id, ${q(p.imageUrl)}, ${arr(p.sizes)}, ${p.stock}, ${p.featured}, ${q(JSON.stringify(p.colors))}::jsonb, ${arr(p.images)} from public.categories c where c.slug = ${q(p.categorySlug)} on conflict (slug) do nothing;`);
}
sql.push("");
sql.push("-- Dummy reviews (replace with real ones later). Re-running replaces ONLY the dummy ones (is_dummy), never real reviews.");
sql.push("delete from public.reviews where is_dummy;");
sql.push("insert into public.reviews (product_id, author_name, rating, title, body, size, color, is_dummy, created_at)");
sql.push("select p.id, v.author_name, v.rating, v.title, v.body, v.size, v.color, true, v.created_at::timestamptz");
sql.push("from (values");
sql.push(seedReviews.map((r) => `  (${q(r.productSlug)}, ${q(r.authorName)}, ${r.rating}, ${q(r.title)}, ${q(r.body)}, ${r.size ? q(r.size) : "null"}, ${r.color ? q(r.color) : "null"}, ${q(r.createdAt)})`).join(",\n"));
sql.push(") as v(slug, author_name, rating, title, body, size, color, created_at)");
sql.push("join public.products p on p.slug = v.slug;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql.join("\n") + "\n");

const d = (s: string) => `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$")}'`;
const dart: string[] = [
  "// GENERATED by `node scripts/generate-seed.ts` from seed/catalog.ts. Do not edit by hand.",
  "// Sample catalogue shown in preview mode (when Supabase isn't configured).",
  "",
  "import '../domain/category.dart';",
  "import '../domain/product.dart';",
  "import '../domain/review.dart';",
  "",
  "const seedCategories = <Category>[",
  ...seedCategories.map((c) => `  Category(slug: ${d(c.slug)}, name: ${d(c.name)}, tagline: ${d(c.tagline)}, imageUrl: ${d(c.imageUrl)}),`),
  "];",
  "",
  "const seedProducts = <Product>[",
  ...seedProducts.map((p, i) => {
    const cat = seedCategories.find((c) => c.slug === p.categorySlug)!;
    const mine = seedReviews.filter((r) => r.productSlug === p.slug);
    const avg = mine.length ? Math.round((mine.reduce((a, r) => a + r.rating, 0) / mine.length) * 100) / 100 : 0;
    return `  Product(id: 'preview-${i}', slug: ${d(p.slug)}, name: ${d(p.name)}, description: ${d(p.description)}, priceCents: ${p.priceCents}, categorySlug: ${d(p.categorySlug)}, categoryName: ${d(cat.name)}, imageUrl: ${d(p.imageUrl)}, sizes: [${p.sizes.map(d).join(", ")}], stock: ${p.stock}, featured: ${p.featured}, active: true, colors: [${p.colors.map((c) => `ProductColor(name: ${d(c.name)}, hex: ${d(c.hex)})`).join(", ")}], images: [${p.images.map(d).join(", ")}], ratingAvg: ${avg}, ratingCount: ${mine.length}),`;
  }),
  "];",
  "",
  "/// Dummy reviews by product slug (preview mode only; the database holds the real ones).",
  "final seedReviewsBySlug = <String, List<Review>>{",
  ...seedProducts.map((p) => {
    const mine = seedReviews.filter((r) => r.productSlug === p.slug);
    return `  ${d(p.slug)}: [${mine.map((r, k) => `Review(id: '${p.slug}-${k}', authorName: ${d(r.authorName)}, rating: ${r.rating}, title: ${d(r.title)}, body: ${d(r.body)}, size: ${r.size ? d(r.size) : "null"}, color: ${r.color ? d(r.color) : "null"}, createdAt: DateTime.utc(${r.createdAt.slice(0, 4)}, ${Number(r.createdAt.slice(5, 7))}, ${Number(r.createdAt.slice(8, 10))}))`).join(", ")}],`;
  }),
  "};",
  "",
];
writeFileSync(new URL("../frontend/lib/features/catalog/data/seed_catalog.dart", import.meta.url), dart.join("\n"));
console.log(`Wrote seed.sql and seed_catalog.dart (${seedCategories.length} categories, ${seedProducts.length} products)`);
